import { useEffect, useMemo, useState } from 'react';
import { DndContext, type DragEndEvent, PointerSensor, useSensor, useSensors } from '@dnd-kit/core';
import { arrayMove, SortableContext, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { AlertCircle, ArrowLeft, Check, CheckCircle2, ChevronDown, ChevronRight, Download, GripVertical, ImagePlus, Pencil, Plus, Save, Trash2 } from 'lucide-react';
import { exportTask } from '../lib/backend';
import { flushPendingSaves, useAppStore } from '../store';
import type { Issue, Todo } from '../types';
import { formatDate, ImageStrip, Modal } from './Common';
import { EditableTaskName } from './EditableTaskName';

export function TaskDetail({ taskId }: { taskId: string }) {
  const store = useAppStore(); const task = store.db.tasks.find((t)=>t.id===taskId);
  const [summaryOpen,setSummaryOpen]=useState(false); const [summary,setSummary]=useState(task?.summary??''); const [summaryImages,setSummaryImages]=useState(task?.summary_images??[]);
  const [completeModal,setCompleteModal]=useState(false); const [exportMessage,setExportMessage]=useState('');
  useEffect(()=>{setSummary(task?.summary??'');setSummaryImages(task?.summary_images??[])},[task?.summary,task?.summary_images]);
  if(!task) return null; const readOnly=task.status==='completed';
  const todos=store.db.todos.filter((x)=>x.task_id===task.id).sort((a,b)=>a.order-b.order); const issues=store.db.issues.filter((x)=>x.task_id===task.id).sort((a,b)=>b.created_at.localeCompare(a.created_at));
  const doExport=async()=>{try{await flushPendingSaves();const path=await exportTask(task.id);setExportMessage(`已导出到 ${path}`)}catch(e){setExportMessage(String(e))}};
  return <section className="view task-detail">
    <div className="detail-topbar"><button className="back-button" onClick={store.closeTask}><ArrowLeft size={17}/> 返回项目空间</button><div className="detail-actions">{readOnly&&<button className="ghost-button" onClick={doExport}><Download size={16}/> 导出 Markdown</button>}{!readOnly&&<button className="primary-button" onClick={()=>setCompleteModal(true)}><CheckCircle2 size={17}/> 标记完成</button>}</div></div>
    <header className="detail-hero"><span className="project-number">PROJECT {String(task.task_no).padStart(2,'0')}</span><h1><EditableTaskName task={task}/></h1><div className="timestamp-row"><span title={formatDate(task.created_at,true)}>创建于 {formatDate(task.created_at)}</span><i/><span title={formatDate(task.last_progress_at,true)}>最近推进 {formatDate(task.last_progress_at)}</span>{readOnly&&<><i/><span>完成于 {formatDate(task.completed_at)}</span></>}</div></header>
    {exportMessage&&<div className="notice" onClick={()=>setExportMessage('')}>{exportMessage}</div>}
    <div className="detail-columns"><TodoPanel todos={todos} taskId={task.id} readOnly={readOnly}/><IssuePanel issues={issues} taskId={task.id} readOnly={readOnly}/></div>
    <section className="summary-panel"><button className="summary-toggle" onClick={()=>setSummaryOpen(!summaryOpen)}><div><span className="eyebrow">PROJECT RETROSPECTIVE</span><h2>项目总结</h2></div>{summaryOpen?<ChevronDown/>:<ChevronRight/>}</button>{summaryOpen&&<div className="summary-editor"><textarea value={summary} onChange={(e)=>setSummary(e.target.value)} placeholder="记录阶段结论、关键经验与最终成果……"/><ImageStrip images={summaryImages} onChange={setSummaryImages}/><div className="editor-actions"><span>总结在项目完成后仍可继续维护</span><button className="primary-button" onClick={()=>store.updateSummary(task.id,summary,summaryImages)}><Save size={16}/> 保存总结</button></div></div>}</section>
    {completeModal&&<CompleteTaskModal taskId={task.id} initialSummary={summary} initialImages={summaryImages} onClose={()=>setCompleteModal(false)}/>}
  </section>;
}

function TodoPanel({todos,taskId,readOnly}:{todos:Todo[];taskId:string;readOnly:boolean}){
  const store=useAppStore(); const [adding,setAdding]=useState(false); const [content,setContent]=useState(''); const [images,setImages]=useState<string[]>([]); const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}));
  const dragEnd=(e:DragEndEvent)=>{if(!e.over||e.active.id===e.over.id)return;const old=todos.findIndex(x=>x.id===e.active.id),next=todos.findIndex(x=>x.id===e.over!.id);store.reorderTodos(taskId,arrayMove(todos,old,next).map(x=>x.id));};
  const add=()=>{if(!content.trim()&&!images.length)return;store.addTodo(taskId,content,images);setContent('');setImages([]);setAdding(false)};
  return <section className="work-panel"><header><div><span className="panel-index">01</span><h2>待办清单</h2></div><span>{todos.filter(x=>x.status==='open').length} 未完成</span></header><div className="work-list"><DndContext sensors={sensors} onDragEnd={dragEnd}><SortableContext items={todos.map(x=>x.id)} strategy={verticalListSortingStrategy}>{todos.map(todo=><SortableTodo key={todo.id} todo={todo} readOnly={readOnly}/>)}</SortableContext></DndContext>{!todos.length&&<p className="panel-empty">把下一步写得足够具体。</p>}</div>{!readOnly&&(adding?<div className="inline-editor"><textarea autoFocus value={content} onChange={e=>setContent(e.target.value)} placeholder="新增待办内容"/><ImageStrip images={images} onChange={setImages}/><div><button className="ghost-button" onClick={()=>setAdding(false)}>取消</button><button className="primary-button" onClick={add}>保存待办</button></div></div>:<button className="add-row" onClick={()=>setAdding(true)}><Plus size={16}/> 新增待办</button>)}</section>
}
function SortableTodo({todo,readOnly}:{todo:Todo;readOnly:boolean}){const store=useAppStore();const [editing,setEditing]=useState(false);const [content,setContent]=useState(todo.content);const [images,setImages]=useState(todo.images);const {attributes,listeners,setNodeRef,transform,transition}=useSortable({id:todo.id,disabled:readOnly});return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition}} className={`work-item ${todo.status==='done'?'is-done':''}`}><button className="drag-handle" {...attributes} {...listeners} disabled={readOnly}><GripVertical size={15}/></button><button className="check-box" onClick={()=>!readOnly&&store.toggleTodo(todo.id)}>{todo.status==='done'&&<Check size={14}/>}</button><span className="todo-no">{String(todo.todo_no).padStart(2,'0')}</span>{editing?<div className="item-editor"><textarea value={content} onChange={e=>setContent(e.target.value)}/><ImageStrip images={images} onChange={setImages}/><button className="text-button" onClick={()=>{store.updateTodo(todo.id,content,images);setEditing(false)}}><Save size={14}/> 保存</button></div>:<><div className="item-main"><p>{todo.content}</p>{todo.images.length>0&&<span className="attachment-count"><ImagePlus size={13}/>{todo.images.length}</span>}</div>{!readOnly&&<div className="item-actions"><button className="icon-button" onClick={()=>setEditing(true)}><Pencil size={14}/></button><button className="icon-button danger" onClick={()=>confirm('确定删除这条待办吗？')&&store.deleteTodo(todo.id)}><Trash2 size={14}/></button></div>}</>}</div>}

function IssuePanel({issues,taskId,readOnly}:{issues:Issue[];taskId:string;readOnly:boolean}){const store=useAppStore();const [adding,setAdding]=useState(false);return <section className="work-panel"><header><div><span className="panel-index">02</span><h2>问题记录</h2></div><span>{issues.filter(x=>x.status==='open').length} 未解决</span></header><div className="work-list">{issues.map(issue=><IssueRow key={issue.id} issue={issue} readOnly={readOnly}/>)}{!issues.length&&<p className="panel-empty">记录阻塞，也记录解决它的路径。</p>}</div>{!readOnly&&(adding?<IssueEditor onCancel={()=>setAdding(false)} onSave={(title,detail,images)=>{store.addIssue(taskId,title,detail,images);setAdding(false)}}/>:<button className="add-row" onClick={()=>setAdding(true)}><Plus size={16}/> 新增问题</button>)}</section>}
function IssueRow({issue,readOnly}:{issue:Issue;readOnly:boolean}){const store=useAppStore();const [open,setOpen]=useState(false);const [editing,setEditing]=useState(false);return <article className={`issue-row ${issue.status==='resolved'?'is-done':''}`}><button className="issue-heading" onClick={()=>setOpen(!open)}>{open?<ChevronDown size={16}/>:<ChevronRight size={16}/>}<AlertCircle size={15}/><span>{issue.title}</span>{issue.status==='resolved'&&<em>已解决</em>}</button>{open&&<div className="issue-detail">{editing?<IssueEditor initial={issue} onCancel={()=>setEditing(false)} onSave={(title,detail,images)=>{store.updateIssue(issue.id,{title,detail,images});setEditing(false)}}/>:<><p>{issue.detail||'暂无详情'}</p>{issue.images.length>0&&<ImageStrip images={issue.images} onChange={()=>{}} disabled/>}{!readOnly&&<div className="item-actions"><button className="text-button" onClick={()=>store.toggleIssue(issue.id)}><CheckCircle2 size={14}/>{issue.status==='open'?'标记已解决':'重新打开'}</button><button className="icon-button" onClick={()=>setEditing(true)}><Pencil size={14}/></button><button className="icon-button danger" onClick={()=>confirm('确定删除这条问题记录吗？')&&store.deleteIssue(issue.id)}><Trash2 size={14}/></button></div>}</>}</div>}</article>}
function IssueEditor({initial,onCancel,onSave}:{initial?:Issue;onCancel:()=>void;onSave:(title:string,detail:string,images:string[])=>void}){const[title,setTitle]=useState(initial?.title??'');const[detail,setDetail]=useState(initial?.detail??'');const[images,setImages]=useState(initial?.images??[]);return <div className="inline-editor"><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="问题标题"/><textarea value={detail} onChange={e=>setDetail(e.target.value)} placeholder="问题现象、排查过程、临时方案……"/><ImageStrip images={images} onChange={setImages}/><div><button className="ghost-button" onClick={onCancel}>取消</button><button className="primary-button" onClick={()=>title.trim()&&onSave(title,detail,images)}>保存问题</button></div></div>}
function CompleteTaskModal({taskId,initialSummary,initialImages,onClose}:{taskId:string;initialSummary:string;initialImages:string[];onClose:()=>void}){const complete=useAppStore(s=>s.completeTask);const[summary,setSummary]=useState(initialSummary);const[images,setImages]=useState(initialImages);return <Modal title="完成项目" onClose={onClose} wide><div className="completion-editor"><span className="eyebrow">CAPTURE THE OUTCOME</span><h3>在合上项目之前，留下值得复用的结论。</h3><textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="项目成果、关键经验、遗留事项……"/><ImageStrip images={images} onChange={setImages}/></div><footer className="modal-actions split"><button className="ghost-button" onClick={()=>{complete(taskId,initialSummary,initialImages);onClose()}}>暂不填写，直接完成</button><button className="primary-button" onClick={()=>{complete(taskId,summary,images);onClose()}}><CheckCircle2 size={16}/> 确认完成</button></footer></Modal>}
